; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_arpeggio=music_data_arpeggio
.endif

music_data_arpeggio:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env_7_mid), .hibyte(@tempo_env_7_mid), 0, 0

.export music_data_arpeggio
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env0,@env3,@env2
	.word @env5,@env0,@env4,@env2

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $00,$cc,$c7,$c4,$c2,$c1,$c0,$00,$06
@env2:
	.byte $00,$c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00
@env5:
	.byte $07,$c7,$c6,$c6,$c5,$00,$04,$c3,$c2,$c1,$c1,$00,$0a
@tempo_env_7_mid:
	.byte $03,$05,$05,$06,$03,$06,$05,$05,$80
@song0ch0:
	.byte $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7
@song0ch0loop:
	.byte $6a, .lobyte(@tempo_env_7_mid), .hibyte(@tempo_env_7_mid), $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7, $6b
	.byte $f7, $e7, $6b, $f7, $e7, $6b, $82
@song0ref35:
	.byte $3d, $83, $00, $85, $41, $83, $00, $85, $42, $83, $00, $85, $44, $83, $00, $85, $3d, $83, $00, $85, $41, $83, $00, $85
	.byte $42, $83, $00, $85, $44, $83, $00, $85
	.byte $ff, $20
	.word @song0ref35
@song0ref70:
	.byte $6b
@song0ref71:
	.byte $3a, $83, $00, $85, $3e, $83, $00, $85, $3f, $83, $00, $85, $41, $83, $00, $85, $3a, $83, $00, $85, $3e, $83, $00, $85
	.byte $3f, $83, $00, $85, $41, $83, $00, $85
	.byte $ff, $20
	.word @song0ref71
	.byte $6b
	.byte $ff, $20
	.word @song0ref35
	.byte $ff, $20
	.word @song0ref35
	.byte $ff, $20
	.word @song0ref70
	.byte $ff, $20
	.word @song0ref71
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ref122:
	.byte $82
@song0ref123:
	.byte $31, $83, $00, $85, $35, $83, $00, $85, $36, $83, $00, $85, $38, $83, $00, $85, $31, $83, $00, $85, $35, $83, $00, $85
	.byte $36, $83, $00, $85, $38, $83, $00, $85
	.byte $ff, $20
	.word @song0ref123
@song0ref158:
	.byte $2e, $83, $00, $85, $32, $83, $00, $85, $33, $83, $00, $85, $35, $83, $00, $85, $2e, $83, $00, $85, $32, $83, $00, $85
	.byte $33, $83, $00, $85, $35, $83, $00, $85
	.byte $ff, $20
	.word @song0ref158
	.byte $ff, $20
	.word @song0ref123
	.byte $ff, $20
	.word @song0ref123
	.byte $ff, $20
	.word @song0ref158
	.byte $ff, $20
	.word @song0ref158
@song0ch1loop:
	.byte $ff, $20
	.word @song0ref122
	.byte $ff, $20
	.word @song0ref123
	.byte $ff, $20
	.word @song0ref158
	.byte $ff, $20
	.word @song0ref158
	.byte $ff, $20
	.word @song0ref123
	.byte $ff, $20
	.word @song0ref123
	.byte $ff, $20
	.word @song0ref158
	.byte $ff, $20
	.word @song0ref158
	.byte $f7, $e7, $f7, $e7
	.byte $ff, $20
	.word @song0ref123
	.byte $ff, $20
	.word @song0ref123
	.byte $ff, $20
	.word @song0ref158
	.byte $ff, $20
	.word @song0ref158
	.byte $ff, $20
	.word @song0ref123
	.byte $ff, $20
	.word @song0ref123
	.byte $ff, $20
	.word @song0ref158
	.byte $ff, $20
	.word @song0ref158
	.byte $fd
	.word @song0ch1loop
@song0ch2:
	.byte $f7, $e7, $f7, $e7
@song0ref265:
	.byte $80
@song0ref266:
	.byte $25, $8b, $29, $8b, $2a, $8b, $2c, $8b, $25, $8b, $29, $8b, $2a, $8b, $2c, $8b, $25, $8b, $29, $8b, $2a, $8b, $2c, $8b
	.byte $25, $8b, $29, $8b, $2a, $8b, $2c, $8b, $22, $8b, $26, $8b, $27, $8b, $29, $8b, $22, $8b, $26, $8b, $27, $8b, $29, $8b
	.byte $22, $8b, $26, $8b, $27, $8b, $29, $8b, $22, $8b, $26, $8b, $27, $8b, $29, $8b
@song0ch2loop:
	.byte $ff, $40
	.word @song0ref265
	.byte $ff, $40
	.word @song0ref266
	.byte $ff, $40
	.word @song0ref266
	.byte $ff, $40
	.word @song0ref266
	.byte $ff, $40
	.word @song0ref266
	.byte $fd
	.word @song0ch2loop
@song0ch3:
	.byte $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7
@song0ch3loop:
	.byte $80
@song0ref359:
	.byte $1e, $8b, $00, $8b, $1e, $8b, $00, $8b, $1e, $8b, $1e, $8b, $1e, $8b, $00, $8b, $1e, $8b, $00, $8b, $1e, $8b, $00, $8b
	.byte $1e, $8b, $00, $a7
	.byte $ff, $1c
	.word @song0ref359
	.byte $ff, $1c
	.word @song0ref359
	.byte $ff, $1c
	.word @song0ref359
	.byte $ff, $1c
	.word @song0ref359
	.byte $ff, $1c
	.word @song0ref359
	.byte $ff, $1c
	.word @song0ref359
	.byte $ff, $1c
	.word @song0ref359
	.byte $ff, $1c
	.word @song0ref359
	.byte $ff, $1c
	.word @song0ref359
	.byte $fd
	.word @song0ch3loop
@song0ch4:
	.byte $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7
@song0ch4loop:
	.byte $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $fd
	.word @song0ch4loop
