; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_arpeggio_mmc5=music_data_arpeggio_mmc5
.endif

music_data_arpeggio_mmc5:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6
	.byte .lobyte(@tempo_env_7_mid), .hibyte(@tempo_env_7_mid), 0, 0

.export music_data_arpeggio_mmc5
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env0,@env3,@env2
	.word @env5,@env0,@env4,@env2

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $00,$cc,$c7,$c4,$c2,$c1,$c0,$00,$06
@env2:
	.byte $00,$c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00
@env5:
	.byte $07,$c7,$c6,$c6,$c5,$00,$04,$c3,$c2,$c1,$c1,$00,$0a
@tempo_env_7_mid:
	.byte $03,$05,$05,$06,$03,$06,$05,$05,$80
@song0ch0:
	.byte $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7
@song0ch0loop:
	.byte $6a, .lobyte(@tempo_env_7_mid), .hibyte(@tempo_env_7_mid), $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7, $6b
	.byte $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7, $6b, $f7, $e7
@song0ref39:
	.byte $6b
@song0ref40:
	.byte $82
@song0ref41:
	.byte $3d, $83, $00, $85, $41, $83, $00, $85, $42, $83, $00, $85, $44, $83, $00, $85, $3d, $83, $00, $85, $41, $83, $00, $85
	.byte $42, $83, $00, $85, $44, $83, $00, $85
	.byte $ff, $20
	.word @song0ref41
@song0ref76:
	.byte $6b
@song0ref77:
	.byte $3a, $83, $00, $85, $3e, $83, $00, $85, $3f, $83, $00, $85, $41, $83, $00, $85, $3a, $83, $00, $85, $3e, $83, $00, $85
	.byte $3f, $83, $00, $85, $41, $83, $00, $85
	.byte $ff, $20
	.word @song0ref77
	.byte $6b, $80
	.byte $ff, $20
	.word @song0ref41
	.byte $ff, $20
	.word @song0ref41
	.byte $ff, $20
	.word @song0ref76
	.byte $ff, $20
	.word @song0ref77
	.byte $ff, $20
	.word @song0ref39
	.byte $ff, $20
	.word @song0ref41
	.byte $ff, $20
	.word @song0ref76
	.byte $ff, $20
	.word @song0ref77
	.byte $6b, $80, $44, $8b, $00, $a7, $44, $8b, $00, $a7, $44, $8b, $00, $a7, $44, $8b, $00, $8b, $44, $8b, $00, $8b, $6b, $41
	.byte $8b, $00, $a7, $41, $8b, $00, $a7, $41, $8b, $00, $a7, $41, $8b, $00, $8b, $41, $8b, $00, $8b, $6b, $42, $8b, $00, $a7
	.byte $42, $8b, $00, $a7, $42, $8b, $00, $a7, $42, $8b, $00, $8b, $42, $8b, $00, $8b, $6b, $3f, $8b, $00, $a7, $3f, $8b, $00
	.byte $a7, $3f, $8b, $00, $a7, $3f, $8b, $00, $8b, $3f, $8b, $00, $8b, $fd
	.word @song0ch0loop
@song0ch1:
@song0ref226:
	.byte $82
@song0ref227:
	.byte $31, $83, $00, $85, $35, $83, $00, $85, $36, $83, $00, $85, $38, $83, $00, $85, $31, $83, $00, $85, $35, $83, $00, $85
	.byte $36, $83, $00, $85, $38, $83, $00, $85
	.byte $ff, $20
	.word @song0ref227
@song0ref262:
	.byte $2e, $83, $00, $85, $32, $83, $00, $85, $33, $83, $00, $85, $35, $83, $00, $85, $2e, $83, $00, $85, $32, $83, $00, $85
	.byte $33, $83, $00, $85, $35, $83, $00, $85
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref262
@song0ch1loop:
	.byte $ff, $20
	.word @song0ref226
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref262
	.byte $80, $38, $8b, $00, $a7, $38, $8b, $00, $a7, $38, $8b, $00, $a7, $38, $8b, $00, $8b, $38, $8b, $00, $8b, $35, $8b, $00
	.byte $a7, $35, $8b, $00, $a7, $35, $8b, $00, $a7, $35, $8b, $00, $8b, $35, $8b, $00, $8b, $36, $8b, $00, $a7, $36, $8b, $00
	.byte $a7, $36, $8b, $00, $a7, $36, $8b, $00, $8b, $36, $8b, $00, $8b, $33, $8b, $00, $a7, $33, $8b, $00, $a7, $33, $8b, $00
	.byte $a7, $33, $8b, $00, $8b, $33, $8b, $00, $8b
	.byte $ff, $20
	.word @song0ref226
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref262
	.byte $80
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref226
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref227
	.byte $ff, $20
	.word @song0ref262
	.byte $ff, $20
	.word @song0ref262
	.byte $fd
	.word @song0ch1loop
@song0ch2:
	.byte $f7, $e7, $f7, $e7
@song0ref483:
	.byte $80
@song0ref484:
	.byte $25, $8b, $29, $8b, $2a, $8b, $2c, $8b, $25, $8b, $29, $8b, $2a, $8b, $2c, $8b, $25, $8b, $29, $8b, $2a, $8b, $2c, $8b
	.byte $25, $8b, $29, $8b, $2a, $8b, $2c, $8b, $22, $8b, $26, $8b, $27, $8b, $29, $8b, $22, $8b, $26, $8b, $27, $8b, $29, $8b
	.byte $22, $8b, $26, $8b, $27, $8b, $29, $8b, $22, $8b, $26, $8b, $27, $8b, $29, $8b
@song0ch2loop:
	.byte $ff, $40
	.word @song0ref483
	.byte $ff, $40
	.word @song0ref484
	.byte $ff, $40
	.word @song0ref484
	.byte $ff, $40
	.word @song0ref484
	.byte $ff, $40
	.word @song0ref484
	.byte $ff, $40
	.word @song0ref484
	.byte $ff, $40
	.word @song0ref484
	.byte $ff, $40
	.word @song0ref484
	.byte $ff, $40
	.word @song0ref484
	.byte $fd
	.word @song0ch2loop
@song0ch3:
	.byte $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7
@song0ch3loop:
	.byte $80
@song0ref589:
	.byte $1e, $8b, $00, $8b, $1e, $8b, $00, $8b, $1e, $8b, $00, $8b, $1e, $8b, $00, $8b, $1e, $8b, $1e, $8b, $1e, $8b, $00, $8b
	.byte $1e, $8b, $00, $a7
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $ff, $1c
	.word @song0ref589
	.byte $fd
	.word @song0ch3loop
@song0ch4:
	.byte $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7
@song0ch4loop:
@song0ref680:
	.byte $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7
	.byte $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7, $fd
	.word @song0ch4loop
@song0ch5:
	.byte $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7
@song0ch5loop:
	.byte $ff, $1c
	.word @song0ref680
	.byte $85, $82
@song0ref733:
	.byte $25, $83, $00, $85, $29, $83, $00, $85, $2a, $83, $00, $85, $2c, $83, $00, $85, $25, $83, $00, $85, $29, $83, $00, $85
	.byte $2a, $83, $00, $85, $2c, $83, $00, $85
	.byte $ff, $20
	.word @song0ref733
@song0ref768:
	.byte $22, $83, $00, $85, $26, $83, $00, $85, $27, $83, $00, $85, $29, $83, $00, $85, $22, $83, $00, $85, $26, $83, $00, $85
	.byte $27, $83, $00, $85, $29, $83, $00, $85
	.byte $ff, $20
	.word @song0ref768
	.byte $ff, $20
	.word @song0ref733
	.byte $ff, $20
	.word @song0ref733
	.byte $ff, $20
	.word @song0ref768
	.byte $ff, $1f
	.word @song0ref768
	.byte $fd
	.word @song0ch5loop
@song0ch6:
	.byte $f7, $e7, $f7, $e7, $f7, $e7, $f7, $e7
@song0ch6loop:
	.byte $ff, $1c
	.word @song0ref680
	.byte $ff, $20
	.word @song0ref40
	.byte $ff, $20
	.word @song0ref41
	.byte $ff, $20
	.word @song0ref77
	.byte $ff, $20
	.word @song0ref77
	.byte $ff, $20
	.word @song0ref41
	.byte $ff, $20
	.word @song0ref41
	.byte $ff, $20
	.word @song0ref77
	.byte $ff, $20
	.word @song0ref77
	.byte $fd
	.word @song0ch6loop
